<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_icon fa fa-eye-slash fa-2x</name>
   <tag></tag>
   <elementGuidId>d57c533a-4b75-450b-ae99-131c53c9b6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-Column2']/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-eye-slash.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c6a6d249-7e67-4d20-a0b3-2841f57e022d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-eye-slash fa-2x</value>
      <webElementGuid>95962a1e-ba72-487b-882f-41e671bf4092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-Column2&quot;)/div[1]/a[1]/i[@class=&quot;icon fa fa-eye-slash fa-2x&quot;]</value>
      <webElementGuid>0495ab62-2423-4bfa-9247-73ae4a06d891</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-Column2']/div/a/i</value>
      <webElementGuid>2d853d8f-0feb-4361-961e-bd40f55c0b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>b6c55cd5-5a37-4e76-b4d8-c7e5d9f082e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
